// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace intinc_vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "intinc_vsix.8c63d8fa-3d11-4e7c-b725-382ab1a94b34";
        public const string Name = "intinc_vsix";
        public const string Description = @"Extension to easily create increasing integers row by row";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Michael Jacobsen";
        public const string Tags = "";
    }
}
